# Generated by Django 3.2.13 on 2023-02-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.FileField(null=True, upload_to='articles'),
        ),
    ]
