# Generated by Django 3.2.13 on 2023-01-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adherents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=25)),
                ('prenom', models.CharField(blank=True, max_length=25)),
                ('nomArabe', models.CharField(blank=True, max_length=25)),
                ('prenomArabe', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=30, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, unique=True)),
                ('dateNaissance', models.DateField(blank=True)),
                ('communes', models.CharField(blank=True, max_length=25)),
                ('adresse', models.CharField(blank=True, max_length=35)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('photo', models.ImageField(upload_to='./adherents/pics')),
                ('recuPaiement', models.FileField(upload_to='./adherents/files')),
            ],
        ),
        migrations.CreateModel(
            name='diplomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.FileField(null=True, upload_to='./adherents/diplomes')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.adherents')),
            ],
        ),
    ]
