# Generated by Django 3.2.13 on 2023-03-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0009_auto_20230308_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherents',
            name='photo',
            field=models.FileField(null=True, upload_to='adhesion'),
        ),
        migrations.AlterField(
            model_name='adherents',
            name='recuPaiement',
            field=models.FileField(null=True, upload_to='adhesion'),
        ),
    ]
